#ifndef MANDELBROT_RENDERPARAMS_H
#define MANDELBROT_RENDERPARAMS_H

const size_t SCREEN_WIDTH = 256 * 3;
const size_t SCREEN_HEIGHT = 144 * 3;

const double FRAMES_PER_SECOND = 30;

const size_t TEXTURE_WIDTH = SCREEN_WIDTH;
const size_t TEXTURE_HEIGHT = SCREEN_HEIGHT;

#endif //MANDELBROT_RENDERPARAMS_H
